# Generated by Django 5.0.2 on 2024-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50, unique=True)),
                ('spread', models.FloatField(default=0.0)),
                ('alert_spread', models.FloatField(default=0.0)),
            ],
        ),
    ]
